name: Upload to Google Drive

on:
  push:
    branches:
      - main  # Specify the branch to trigger the workflow

jobs:
  upload_to_gdrive:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Decode and save the service account credentials to service_account.json
      - name: Decode and Save Service Account Credentials
        run: |
          echo "${{ secrets.GDRIVE_SERVICE_ACCOUNT }}" | base64 --decode > service_account.json
          if [ -f "service_account.json" ]; then
            echo "Service account file decoded successfully."
          else
            echo "Failed to decode service account file."
            exit 1
          fi

      # Step 4: Install dependencies for Google Drive API
      - name: Install Dependencies
        run: |
          pip install --no-cache-dir google-api-python-client google-auth-httplib2 google-auth-oauthlib

      # Step 5: Compress files to a single zip file for upload
      - name: Compress Files
        run: |
          zip -r website.zip . -x ".git/*" ".github/*"
          ls -al  # Display list of files to confirm zip creation

      # Step 6: Run the Python script to upload to Google Drive
      - name: Upload to Google Drive
        run: |
          python upload_to_gdrive.py
